name: test by nodejs jest framework 
on:
    workflow_dispatch:
    push:
        paths-ignore:
            - 'README.md'
            - '**.yml'
jobs:
    test_job:
        runs-on: ubuntu-latest
        env:
            var2: ${{ vars.var2 }}
            var3: ${{ secrets.var3 }}
        steps:
          - uses: actions/checkout@v4
          - name: Use Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20.x'
          - run: npm i -D
          - run: npm test